project:
  type: website

website:
  page-navigation: true
  title: "STAR-DS"
  description: "Homepage for 'STatisticians Advancing in R for Data Science (STAR-DS) ', SDSS 2026."
  site-url: "http://tinyurl.com/STAR-DS"

  repo-url: http://github.com/mmadoliat/STAR-DS/
  repo-actions: [edit, issue]

  open-graph: true
  twitter-card:
    creator: "@mmadoliat"
    image: "images/twitter-card.png"

  sidebar:
    background: "#FFCC00" # MU Yellow
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: http://github.com/mmadoliat/STAR-DS/
        text: "GitHub organization"
      - icon: code-square
        href: http://tinyurl.com/STAR-DS
        text: "Bitly"
      - icon: person-fill
        href: http://bit.ly/RS-dna
        text: "dna RStudio"

    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: index.qmd
            text: Schedule
      - section: "Slides"
        contents:
          - href: slides/Topic2.qmd
            text: Shiny
          - href: slides/Topic3.qmd
            text: RCpp
          - href: slides/Topic4.qmd
            text: Python in R
          - href: slides/Topic5.qmd
            text: R package
          - href: slides/Topic6.qmd
            text: GitHub / CRAN submission
      - section: "Hands-on / HW"
        contents:
          - href: hands-on/HO2.qmd
            text: Shiny
          - href: hands-on/HO3.qmd
            text: RCpp
          - href: hands-on/HW1.qmd
            text: First Week HW
          - href: 
            text: Python in R
          - href: 
            text: R Package
          - href: 
            text: GitHub
      - section: "Miscellaneous"
        contents:
          - href: course-links.qmd
            text: Useful links
          - href: misc/cheatsheets.qmd
            text: Cheatsheets

  page-footer:
    right: "This page is built with [Quarto](http://quarto.org/)."
    left: "&copy; Copyright 2025, Mehdi Maadooliat, Jaihee Choi and Daniel Cirkovic"
    background: "#FFCC00" # Arylide Yellow
    
format:
  html:
    theme:
      light: [cosmo, style/mu.scss]
      dark: [cosmo, style/mu.scss, style/dark.scss]
    linkcolor: "#003366" # Glossy Grape
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y-dark
    code-link: true

execute:
  freeze: auto

editor: visual
